feat: create a new API for SMAT.
spgroup/SMAT pull request #2
Opened 2022-07-21 00:57 UTC by jpedroh

2022-08-03 17:55 UTC, leusonmario requested changes

2022-08-03 17:55 UTC, leusonmario commented on nimrod/project_info/merge_scenario.py
> +        self.merge_scenario = Commit()
Talvez seria bom mudar o nome dessa classe Comit para MergeScenarioInformation, pois ela tem informações de não apenas um commit.

2022-08-03 17:55 UTC, leusonmario commented on nimrod/proj/semantic_study.py
> +    if config.get('input_path'):
Procurei, mas não encontrei, onde o arquivo de configuração foi atualizado com este novo parâmetro. Foi feito esta atualização?

2022-08-03 17:55 UTC, leusonmario commented on nimrod/tools/randoop_modified.py
> +            '--time-limit=10',
Deixar os 300 ainda, certo?
Creio que depois podemos receber como parâmetro o tempo que queremos usar as ferramentas.

2022-08-03 18:31 UTC, jpedroh commented on nimrod/tools/randoop_modified.py
> +            '--time-limit=10',
Alterado, tinha reduzido para poder testar mais facilmente ;D

2022-08-03 18:33 UTC, jpedroh commented on nimrod/proj/semantic_study.py
> +    if config.get('input_path'):
Eu acabei não adicionando no arquivo `nimrod/tests/env-config.json`. Vou adicionar a propriedade.

2022-08-03 18:34 UTC, jpedroh commented on nimrod/project_info/merge_scenario.py
> +        self.merge_scenario = Commit()
Salvo engano, acho que essa classe Merge Scenario acabou ficando sem utilidade com a nova classe SmatInput. Podemos ver de talvez mover a classe SMATInput para esse diretório - e aí sim viraria MergeScenario?

2022-08-03 23:06 UTC, leusonmario commented on nimrod/project_info/merge_scenario.py
> +        self.merge_scenario = Commit()
Entendi. Poderia ser uma alternativa mesmo.

2022-08-10 17:51 UTC, pauloborba requested changes

2022-08-10 17:51 UTC, pauloborba commented on nimrod/input_parsing/input_parser.py
> +
@jpedroh coloca aqui um comentário só explicando qual o formato do arquivo, e que esse código faz o parser... se o formato já tiver explicado no README, pode aqui simplesmente referenciar lá. seria melhor.

2022-08-10 17:51 UTC, pauloborba commented on nimrod/proj/project_dependencies.py
> +        # self.path_hash_csv = self.config["path_hash_csv"]
por que não remover esta linha?

2022-08-10 17:51 UTC, pauloborba commented on nimrod/proj/semantic_study.py
> +            'DEPRECATED: Providing input data with `path_hash_csv` is deprecated and will be removed in future versions of SMAT. Use `input_path` instead.')
essas opções estão bem explicadas no README?

2022-08-10 17:51 UTC, pauloborba commented on nimrod/project_info/merge_scenario.py
a princípio, o nimrod não tem nada a ver com merge_scenario. eventualmente a gente deveria renomear, relocar essas classes para que o projeto seja conceitualmente mais claro

2022-08-10 17:51 UTC, pauloborba commented on nimrod/report_metrics/coverage/coverage_report.py
>          listaCoberturaProjeto = ["randoop X: cobertura metodo SUA", "randoop Y: cobertura metodo SUA",
como eventualmente esse código pode ser usado por outros grupos de pesquisa, seria importante evitar o português na saída gerada pela ferramenta. seria importante também colocar na saída o significado/legenda das abreviações

2022-08-10 17:51 UTC, pauloborba commented on nimrod/report_metrics/coverage/coverage_report.py
> +    def _decomposeTarget(self, targets: "dict[str,list[str]]"):
seria interessante adicionar um comentário para o método

2022-08-10 21:02 UTC, jpedroh commented on nimrod/input_parsing/input_parser.py
> +
O formato não está descrito no README. Vou adicionar uma seção informando sobre a entrada e referenciar no código. ;D

2022-08-10 21:02 UTC, jpedroh commented on nimrod/proj/project_dependencies.py
> +        # self.path_hash_csv = self.config["path_hash_csv"]
Bem notado, vou remover a linha.

2022-08-10 21:03 UTC, jpedroh commented on nimrod/proj/semantic_study.py
> +            'DEPRECATED: Providing input data with `path_hash_csv` is deprecated and will be removed in future versions of SMAT. Use `input_path` instead.')
Não, vou adicionar essa documentação.

2022-08-10 21:08 UTC, jpedroh commented on nimrod/project_info/merge_scenario.py
Acho que isso entraria naquela separação que comentamos na última reunião. Podemos ver futuramente um modelo mais forte para SMAT.

2022-08-10 21:09 UTC, jpedroh commented on nimrod/report_metrics/coverage/coverage_report.py
>          listaCoberturaProjeto = ["randoop X: cobertura metodo SUA", "randoop Y: cobertura metodo SUA",
Acho que podemos adicionar uma tarefa de refatoração posterior para isso. Não sei quais outras ferramentas estão utilizando este reporte... @ToniMaciel @leusonmario alguma ideia?

2022-08-11 00:04 UTC, jpedroh commented on nimrod/input_parsing/input_parser.py
> +
Documentação adicionada no README! Também adicionei um comentário em InputParser informando um pouco o propósito da interface.

2022-08-16 00:50 UTC, ToniMaciel approved these changes

2022-08-16 11:53 UTC, leusonmario approved these changes

2022-08-16 17:42 UTC, merged